title: Programmer blog 
description: Any posts on the topic of programming
theme: just-the-docs

url: https://KosarevDmitry.github.io/tips

aux_links:
  Template Repository: https://github.com/KosarevDmitry/tips
